### ISSUE TITLE
Make fire come from mouth

### ISSUE THREAD

**Issue by Cammac7** [Cammac7/Game-Design-Project#16]
Right now the laser comes out as he raises his head. We need to make it so that he lifts his head, opens his mouth, THEN the laser comes out, then the lowering animation completes

**Comment by Harmonickey** [comment]
This can happen by attaching a script object to the 'shooting' animation controller.

**Comment by Cammac7** [comment]
I don't think I'll add it as a separate ticket, but his mouth is still getting stuck open

**Comment by Cammac7** [comment]
Ok it's coming right out of his mouth now! Hooray!
