### ISSUE TITLE
Add bar+backend for experience+leveling up

### ISSUE THREAD

**Issue by Cammac7** [Cammac7/Game-Design-Project#22]
We need a bar like the health bar to grow every time you damage an enemy

**Comment by Harmonickey** [comment]
I can probably do this.  I assume we want the color to be blue?

**Comment by Cammac7** [comment]
Ok, bar now resets to zero everytime you level up. Also takes 3x as much xp to reach each subsequent level.

**Comment by Cammac7** [comment]
Made it so it upgrades you weapon when you level up, we need some more with that though
