### ISSUE TITLE
Enemy implementation

### ISSUE THREAD

**Issue by Cammac7** [Cammac7/Game-Design-Project#27]
Currently only two enemies, need them to keep coming and also get progressively stronger.

**Comment by Harmonickey** [comment]
@Brian-Bowyer Can you work on getting spawning to work?  I think implementing a single spawn point for now is good, and then we can insert more later as the map grows.

**Comment by Harmonickey** [comment]
Spawn points should just be dynamic, off screen by about 100 units to the left and right of the player.

**Comment by Cammac7** [comment]
Spawn point for bees created. Expandable array, so more points can be added.
