### ISSUE TITLE
Make explode (death sounds)

### ISSUE THREAD

**Issue by Cammac7** [Cammac7/Game-Design-Project#29]
need a few explosion sounds ("explode") when enemies die.

**Comment by Cammac7** [comment]
there's an "enemy death.mp3" i added, just need to attach it to the hives

**Comment by Cammac7** [comment]
i think the move is to just play it when the nests explode

**Comment by Cammac7** [comment]
Ok, so I see that these are placed for the enemies, but they aren't playing.. . .thoughts?

**Comment by Harmonickey** [comment]
because the game object is destroyed before most of the audio is played, we have to play the audio with an object that is not destroyed

**Comment by Cammac7** [comment]
^Ohh I see. Can we trigger the audio to play and then destroy it or will the audio stop?

**Comment by Harmonickey** [comment]
No matter what, even if we play the audio, if we do it this way then when the object gets destroyed, it's mid way through playing the audio, so the audio would cease

**Comment by Cammac7** [comment]
Damn, That makes sense though.

**Comment by Harmonickey** [comment]
works now
