### ISSUE TITLE
Background Cycler

### ISSUE THREAD

**Issue by Harmonickey** [Cammac7/Game-Design-Project#30]
@Brian-Bowyer We need to make sure that this is continuously adding new tiles, like in Blorb.

For now this will actually be the easiest just so we can have an infinite level.  Spawn points should just be dynamic, off screen by about 100 units to the left and right of the player.

**Comment by Harmonickey** [comment]
However, the tiles only increase to the right.  There should be a boundary to the left.

**Comment by Cammac7** [comment]
We only need tiles increasing right, right? I thought we don't want them going back left.

**Comment by Brian-Bowyer** [comment]
There is now a level, even though it's not infinite, so I feel safe in calling this one effectively done.
